#intro to numpy

In [1]:
!pip install numpy

In [ ]:
!pip install numpy

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

even =[6,8,10,12,14]
lem(even)

In [4]:
even =[6,8,10,12,14] 
len(even)

5

In [5]:
even_array=np.array(even)
even_array

array([ 6,  8, 10, 12, 14])

In [7]:
even_array[-1]

14

In [8]:
even_array[1:4]  #slicing the array

array([ 8, 10, 12])

In [9]:
type(even_array)

numpy.ndarray

# different betwn list and array
* Numpy array are faster then python list
* Numpy array are memory effecient then python list
* Numoy array suppports homogenous datatype while python list supports multiple data types

In [11]:
np.ones(3,dtype=np.float16)

array([1., 1., 1.], dtype=float16)

In [ ]:
num=np.random.randint(0,10) #non-deterministic algorithm
print(num)

: 

In [18]:
np.random.seed(2) #deterministic algorithm
np.random.randint(0,10)

8

In [23]:
np.random.seed(2024)
x=np.random.randint(1, 10,size=500000)

In [25]:
x_list=x.tolist()
#x_list

In [26]:
a=[1,2,3]
sq=[]
for item in a:
    sq.append(item**2)
sq

[1, 4, 9]

In [28]:
[item**2 for item in a]

[1, 4, 9]

In [29]:
%%time
sq=[item**2 for item in x_list]

CPU times: total: 109 ms
Wall time: 149 ms


In [30]:
%%time
sq=x**2

CPU times: total: 31.2 ms
Wall time: 5 ms


#.linspace()

In [36]:
np.linspace(0,1,5)#5gaps from 0 to 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
np.arange(11,24,1)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [1]:
# start 11
# stop 24
#s tep 1

In [41]:
x=np.array([4,9])
y=np.array([2,3])
x+y

array([ 6, 12])

In [42]:
x%y

array([0, 0])

In [43]:
x/y

array([2., 3.])

# statistics

In [45]:
np.random.seed(0)
x=np.random.randint(1,20, size=20)
x

array([13, 16,  1,  4,  4,  8, 10, 19,  5,  7, 13,  2,  7,  8, 15, 18,  6,
       14,  9, 10])

In [46]:
np.mean(x)

9.45

In [48]:
np.median(x)

8.5

In [49]:
from scipy.stats import mode
mode(x)

ModeResult(mode=4, count=2)

In [51]:
np.var(x)#varience

25.9475

# 2D array

In [55]:
matrix=np.array( [[1,2,3],[2,3,4],[3,4,5]] )
matrix

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [53]:
matrix.ndim


2

In [56]:
matrix[1: , 1:]

array([[3, 4],
       [4, 5]])

In [91]:
matrix[1: 2,2:3]

array([[4]])

In [63]:
matrix[0:,:2]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [71]:
matrix[1:2,2:]+matrix

array([[2, 3]])

In [82]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[9,10],[11,12]])


In [83]:
a.shape

(2, 3)

In [84]:
output=np.dot(a,b)

In [85]:
b.shape

(3, 2)

In [86]:
output

array([[ 58,  64],
       [139, 154]])

In [88]:
det=np.linalg.det(output)

In [89]:
np.round(det,2)

36.0

# convert 2d into 1d

In [92]:
x=np.array([[4,5,6],[3,2,0]])

In [93]:
print(f"dimension= {x.ndim}")

dimension= 2


In [96]:
xOneD=x.flatten()
print(xOneD)
print(f"dimension= {xOneD.ndim}")

[4 5 6 3 2 0]
dimension= 1


# convert 1d into 2d

In [99]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
x.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [104]:
np.sum(x)

45

In [110]:
x.sum(axis=0) #horizonatal sum 

45

In [111]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
x.sum(axis=1)

array([ 6, 15])

In [114]:
x.sum(axis=0)

array([5, 7, 9])